# Generated by Django 5.2.7 on 2025-11-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
        ('positions', '__first__'),
        ('structure', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employees.employee')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='positions.post')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='structure.subdivision')),
            ],
            options={
                'unique_together': {('employee', 'subdivision', 'post')},
            },
        ),
    ]
