# Generated by Django 5.2.7 on 2025-11-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('structure', '0002_subdivision_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='schedule.lessontype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='structure.location')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='employees.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.subject')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
