# Generated by Django 5.2.7 on 2025-11-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivisions', to='structure.location')),
                ('id_type_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivisions', to='structure.typedivision')),
            ],
        ),
    ]
